### ISSUE TITLE
Crashes if we try to assign to an rvalue

### ISSUE THREAD

**Issue by jyn514** [jyn514/lox#11]
```
$ ./jlox
> 2 = 1;
<stdin>:1:3: error: INTERNAL error: pointers not implemented
Exception in thread "main" java.lang.ClassCastException: lox.java.Expr$Literal cannot be cast to lox.java.Expr$Symbol
        at lox.java.Parser.assignment(Parser.java:223)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.comma(Parser.java:209)
        at lox.java.Parser.expression(Parser.java:204)
        at lox.java.Parser.expressionStatement(Parser.java:184)
        at lox.java.Parser.statement(Parser.java:95)
        at lox.java.Parser.declaration(Parser.java:48)
        at lox.java.Parser.runPass(Parser.java:32)
        at lox.java.Parser.runPass(Parser.java:15)
        at lox.java.Lox.run(Lox.java:49)
        at lox.java.Lox.runPrompt(Lox.java:114)
        at lox.java.Lox.main(Lox.java:38)
```

**Comment by jyn514** [comment]
Related:

```
$ ./jlox
> 2();
<stdin>:1:2: error: INTERNAL error: first class functions and function pointers not implemented
Exception in thread "main" java.lang.ClassCastException: lox.java.Expr$Literal cannot be cast to lox.java.Expr$Symbol
        at lox.java.Parser.call(Parser.java:324)
        at lox.java.Parser.postfixUnary(Parser.java:302)
        at lox.java.Parser.prefixUnary(Parser.java:297)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.multiplication(Parser.java:272)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.addition(Parser.java:267)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.bitwise(Parser.java:262)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.comparison(Parser.java:257)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.equality(Parser.java:252)
        at lox.java.Parser.and(Parser.java:240)
        at lox.java.Parser.or(Parser.java:230)
        at lox.java.Parser.assignment(Parser.java:215)
        at lox.java.Parser.parseBinary(Parser.java:406)
        at lox.java.Parser.comma(Parser.java:209)
        at lox.java.Parser.expression(Parser.java:204)
        at lox.java.Parser.expressionStatement(Parser.java:184)
        at lox.java.Parser.statement(Parser.java:95)
        at lox.java.Parser.declaration(Parser.java:48)
        at lox.java.Parser.runPass(Parser.java:32)
        at lox.java.Parser.runPass(Parser.java:15)
        at lox.java.Lox.run(Lox.java:49)
        at lox.java.Lox.runPrompt(Lox.java:114)
        at lox.java.Lox.main(Lox.java:38)
```

**Comment by jyn514** [comment]
As of https://github.com/jyn514/lox/commit/d9dc1f3effdad0e7b8ac491b10fa4ab43d75ea24, no longer crashes, but assigning to the result of an expression is not supported. This is not a problem because we haven't implemented pointers yet.
